version: "3"
services:
  groestlcoind:
    restart: unless-stopped
    container_name: groestlcoind
    image: nicolasdorier/docker-groestlcoin:2.16.3
    environment:
      GROESTLCOIN_EXTRA_ARGS: |
        rpcport=43782
        ${NETWORK:-regtest}=1
        port=39388
        whitelist=0.0.0.0/0
    expose:
    - "43782"
    - "39388"
    volumes:
    - "./groestlcoin_datadir:/data"
  clightning_groestlcoin:
    image: kukks/grs-clightning:latest
    stop_signal: SIGKILL
    container_name: clightning_groestlcoin
    restart: unless-stopped
    environment:
      LIGHTNINGD_NETWORK: ${NETWORK:-regtest}
      LIGHTNINGD_OPT: |
        bitcoin-datadir=/etc/groestlcoin
        bitcoin-rpcconnect=groestlcoind
        bitcoin-rpcport=43782
        log-level=debug
        announce-addr=${HOST}:9737
        bind-addr=0.0.0.0:9735
        network=${NETWORK:-regtest}
        alias=${LIGHTNING_ALIAS}
    volumes:
    - "./clightning_groestlcoin_datadir:/root/.lightning"
    - "./groestlcoin_datadir:/etc/groestlcoin"
    ports:
    - "9735:9735"
    links:
    - groestlcoind